version: '3.8'

services:
  ollama:
    hostname: ollama
    container_name: ollama
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin          # MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: password       # MongoDB root password    # Replace with actual path on your host
